version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - 8080:8080
    restart: always
    tty: true
    volumes:
      - ./frontend/app:/app
    working_dir: /app
    command: yarn serve

  backend:
    container_name: "backend"
    build: ./backend
    volumes:
      - ./backend:/backend

    ports:
      - 3000:3000
    restart: always
    tty: true
