version: '3.7'

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: yarn dev

volumes:
  postgres_data:
