version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - 8080:8080
    restart: always
    tty: true
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: yarn serve

  backend:
    container_name: "backend"
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 3000
    restart: always
    tty: true
